#!/usr/bin/env bash
# Copyright 2024 AllNew LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# gate-health.sh - Quality score vs gate pass rate correlation analysis
#
# Usage:
#   gate-health.sh [--help]
#
# Environment variables:
#   CLAUDE_PLUGIN_DATA  If set, reads quality assessments from
#                       ${CLAUDE_PLUGIN_DATA}/qc/ and gate results from
#                       ${CLAUDE_PLUGIN_DATA}/qc/gate-results/.
#   (If CLAUDE_PLUGIN_DATA is not set, falls back to docs/pipeline/ for
#    quality assessments and docs/pipeline/gate-result-*.json for gate results.)
#
# Description:
#   Joins quality self-assessment data with gate result data on phase_id.
#   Categorizes each phase into one of four quadrants:
#     Healthy         (quality pass + gate pass)
#     Gate Misaligned (quality pass + gate fail)
#     Gate Too Lenient(quality warn/fail + gate pass)
#     Correctly Caught(quality warn/fail + gate fail)
#   Prints a correlation matrix and health score.

set -euo pipefail

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------
usage() {
    cat <<'EOF'
Usage: gate-health.sh [--help]

Analyze correlation between quality self-assessment scores and gate pass rates.

Environment variables:
  CLAUDE_PLUGIN_DATA   Read quality assessments from ${CLAUDE_PLUGIN_DATA}/qc/
                       and gate results from ${CLAUDE_PLUGIN_DATA}/qc/gate-results/.
                       If not set, falls back to docs/pipeline/ in the current
                       working directory.

Output:
  Prints a per-phase correlation table with four-quadrant diagnosis and a
  health score summary. If no gate result data is found, prints a helpful tip.
  Informational messages are printed to stderr.

Exit codes:
  0  Success (including the case where no data or gate results are found)
  1  Unexpected error
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    usage
    exit 0
fi

# ---------------------------------------------------------------------------
# Resolve data directories
# ---------------------------------------------------------------------------
if [ -n "${CLAUDE_PLUGIN_DATA:-}" ]; then
    QC_DIR="${CLAUDE_PLUGIN_DATA}/qc"
    GATE_DIR="${CLAUDE_PLUGIN_DATA}/qc/gate-results"
    echo "Data source: ${QC_DIR}" >&2
else
    QC_DIR="$(pwd)/docs/pipeline"
    GATE_DIR="$(pwd)/docs/pipeline"
    echo "Data source: ${QC_DIR} (fallback; set CLAUDE_PLUGIN_DATA for central store)" >&2
fi

# ---------------------------------------------------------------------------
# Handle missing quality assessment directory
# ---------------------------------------------------------------------------
if [ ! -d "${QC_DIR}" ]; then
    echo "No quality assessment data found in ${QC_DIR}"
    exit 0
fi

# ---------------------------------------------------------------------------
# Collect quality assessment files
# ---------------------------------------------------------------------------
qa_files=""
qa_count=0
while IFS= read -r f; do
    if [ -n "$f" ]; then
        qa_files="${qa_files}${f}"$'\n'
        qa_count=$((qa_count + 1))
    fi
done < <(find "${QC_DIR}" -maxdepth 1 -name 'quality-self-assessment-*.json' -type f | sort)

if [ "$qa_count" -eq 0 ]; then
    echo "No quality assessment data found in ${QC_DIR}"
    exit 0
fi

# ---------------------------------------------------------------------------
# Check for gate result data
# ---------------------------------------------------------------------------
gate_count=0
if [ -d "${GATE_DIR}" ]; then
    while IFS= read -r f; do
        [ -n "$f" ] && gate_count=$((gate_count + 1))
    done < <(find "${GATE_DIR}" -maxdepth 1 -name 'gate-result-*.json' -type f 2>/dev/null | sort)
fi

if [ "$gate_count" -eq 0 ]; then
    echo ""
    echo "=== Gate Health Report ==="
    echo "Data source: ${QC_DIR}"
    echo ""
    echo "No gate result data found in ${GATE_DIR}/gate-results/"
    echo ""
    echo "Tip: Gate results are generated by pipeline gate checkers. This analysis"
    echo "requires both quality assessments AND gate results."
    echo "=== End of Report ==="
    exit 0
fi

# ---------------------------------------------------------------------------
# JSON extraction helpers (awk, no jq)
# ---------------------------------------------------------------------------
extract_json_str() {
    local key="$1"
    local file="$2"
    awk -v key="$key" '
    {
        pattern = "\"" key "\"[[:space:]]*:[[:space:]]*\"([^\"]*)\""
        if (match($0, pattern)) {
            s = substr($0, RSTART, RLENGTH)
            sub("^\"" key "\"[[:space:]]*:[[:space:]]*\"", "", s)
            sub("\"$", "", s)
            print s
            exit
        }
    }
    ' "$file"
}

# ---------------------------------------------------------------------------
# Build lookup: phase_id -> gate result
# Gate result JSON: { "phase_id": "...", "result": "pass|fail", ... }
# ---------------------------------------------------------------------------
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

gate_map="${tmp_dir}/gate_map.txt"
touch "$gate_map"

while IFS= read -r f; do
    [ -z "$f" ] && continue
    phase_id="$(extract_json_str "phase_id" "$f")"
    result="$(extract_json_str "result" "$f")"
    [ -z "$phase_id" ] && continue
    [ -z "$result" ] && result="unknown"
    printf '%s|%s\n' "$phase_id" "$(echo "$result" | tr '[:lower:]' '[:upper:]')" >> "$gate_map"
done < <(find "${GATE_DIR}" -maxdepth 1 -name 'gate-result-*.json' -type f | sort)

# ---------------------------------------------------------------------------
# Build correlation table
# ---------------------------------------------------------------------------
corr_file="${tmp_dir}/corr.txt"
touch "$corr_file"

healthy=0
gate_misaligned=0
gate_too_lenient=0
correctly_caught=0
total_phases=0

while IFS= read -r f; do
    [ -z "$f" ] && continue

    phase_id="$(extract_json_str "phase_id" "$f")"
    overall="$(extract_json_str "overall" "$f")"
    [ -z "$phase_id" ] && phase_id="$(basename "$f" .json | sed 's/quality-self-assessment-//')"
    [ -z "$overall" ] && overall="unknown"
    quality_upper="$(echo "$overall" | tr '[:lower:]' '[:upper:]')"

    # Look up gate result for this phase_id
    gate_result="$(awk -F'|' -v pid="$phase_id" '$1 == pid { print $2; exit }' "$gate_map")"
    [ -z "$gate_result" ] && gate_result="N/A"

    # Determine quality pass vs warn/fail
    case "$quality_upper" in
        PASS) quality_side="PASS" ;;
        *)    quality_side="WARN/FAIL" ;;
    esac

    # Determine gate pass vs fail
    case "$gate_result" in
        PASS) gate_side="PASS" ;;
        FAIL) gate_side="FAIL" ;;
        *)    gate_side="N/A" ;;
    esac

    # Diagnose
    if [ "$gate_side" = "N/A" ]; then
        diagnosis="No Gate Data"
    elif [ "$quality_side" = "PASS" ] && [ "$gate_side" = "PASS" ]; then
        diagnosis="Healthy"
        healthy=$((healthy + 1))
    elif [ "$quality_side" = "PASS" ] && [ "$gate_side" = "FAIL" ]; then
        diagnosis="Gate Misaligned"
        gate_misaligned=$((gate_misaligned + 1))
    elif [ "$quality_side" = "WARN/FAIL" ] && [ "$gate_side" = "PASS" ]; then
        diagnosis="Gate Too Lenient"
        gate_too_lenient=$((gate_too_lenient + 1))
    else
        diagnosis="Correctly Caught"
        correctly_caught=$((correctly_caught + 1))
    fi

    total_phases=$((total_phases + 1))
    printf '%s|%s|%s|%s\n' "$phase_id" "$quality_upper" "$gate_result" "$diagnosis" >> "$corr_file"

done <<< "$qa_files"

# ---------------------------------------------------------------------------
# Correlation matrix counts
# ---------------------------------------------------------------------------
# quality_pass_gate_pass, quality_pass_gate_fail, quality_wf_gate_pass, quality_wf_gate_fail
qp_gp=0; qp_gf=0; qwf_gp=0; qwf_gf=0
while IFS='|' read -r _phase quality gate _diag; do
    [ -z "$_phase" ] && continue
    case "$quality" in
        PASS)
            case "$gate" in
                PASS) qp_gp=$((qp_gp + 1)) ;;
                FAIL) qp_gf=$((qp_gf + 1)) ;;
            esac
            ;;
        *)
            case "$gate" in
                PASS) qwf_gp=$((qwf_gp + 1)) ;;
                FAIL) qwf_gf=$((qwf_gf + 1)) ;;
            esac
            ;;
    esac
done < "$corr_file"

# ---------------------------------------------------------------------------
# Health score
# ---------------------------------------------------------------------------
if [ "$total_phases" -gt 0 ]; then
    health_pct=$(( (healthy * 100) / total_phases ))
else
    health_pct=0
fi

# ---------------------------------------------------------------------------
# Print report
# ---------------------------------------------------------------------------
echo ""
echo "=== Gate Health Report ==="
echo "Data source: ${QC_DIR}"
echo "Phases analyzed: ${total_phases}"
echo ""

# Correlation table header
printf '%-16s | %-7s | %-6s | %s\n' "Phase" "Quality" "Gate" "Diagnosis"
printf '%s\n' "----------------+---------+--------+------------------"

while IFS='|' read -r phase_id quality gate diagnosis; do
    [ -z "$phase_id" ] && continue
    printf '%-16s | %-7s | %-6s | %s\n' "$phase_id" "$quality" "$gate" "$diagnosis"
done < "$corr_file"

echo ""
echo "Correlation Matrix:"
printf '                  %-12s %-12s\n' "Gate PASS" "Gate FAIL"
printf '  Quality PASS      %-12s %-12s\n' "$qp_gp" "$qp_gf"
printf '  Quality WARN/FAIL %-12s %-12s\n' "$qwf_gp" "$qwf_gf"
echo ""
echo "Health Score: ${healthy}/${total_phases} phases healthy (${health_pct}%)"
echo ""
echo "Interpretation:"
echo "  - \"Gate Too Lenient\" phases: Gate conditions may need strengthening"
echo "  - \"Gate Misaligned\" phases: Quality criteria may be incomplete"
if [ "$health_pct" -ge 80 ]; then
    echo "  - High health score (>80%): Quality and gates are well-aligned"
else
    echo "  - Low health score (<80%): Review gate conditions and quality criteria alignment"
fi
echo ""
echo "=== End of Report ==="
